# Generated by Django 4.1.3 on 2023-03-06 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.TextField(max_length=16, null=True, validators=[django.core.validators.MinLengthValidator(16, 'The Card number must have 16 digits')]),
        ),
    ]
