# Generated by Django 4.1.3 on 2023-06-06 04:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='auction_image')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=256)),
                ('item_description', models.TextField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('starting_price', models.FloatField(blank=True, default=100.0, null=True)),
                ('current_bid', models.FloatField(blank=True, null=True)),
                ('is_sold', models.BooleanField(blank=True, default=False, null=True)),
                ('item_category', models.CharField(blank=True, choices=[('art', 'Art'), ('antiques', 'Antiques'), ('books & magazines', 'Books & Magazines'), ('cameras & photo', 'Cameras & Photo'), ('cell phones & accessories', 'Cell Phones & Accessories'), ('clothing, shoes & accessories', 'Clothing, Shoes & Accessories'), ('coins & paper money', 'Coins & Paper Money'), ('collectibles', 'Collectibles'), ('computers/tablets & networking', 'Computers/Tablets & Networking'), ('consumer electronics', 'Consumer Electronics'), ('crafts', 'Crafts'), ('dolls & bears', 'Dolls & Bears'), ('everything else', 'Everything Else'), ('gift cards & coupons', 'Gift Cards & Coupons'), ('health & beauty', 'Health & Beauty'), ('jewelry & watches', 'Jewelry & Watches'), ('music', 'Music'), ('musical instruments & gear', 'Musical Instruments & Gear'), ('pet supplies', 'Pet Supplies'), ('pottery & glass', 'Pottery & Glass'), ('sporting goods', 'Sporting Goods'), ('stamps', 'Stamps'), ('tickets & experiences', 'Tickets & Experiences'), ('toys & hobbies', 'Toys & Hobbies'), ('video games & consoles', 'Video Games & Consoles')], max_length=256, null=True)),
                ('item_location', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuctionWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.auctionitem')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('transaction_amount', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='bid',
            name='Auction_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='sellingitem',
            name='is_auction_item',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='is_dispatched',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_price',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, choices=[('mumbai', 'Mumbai'), ('delhi', 'Delhi '), ('bengluru', 'Bengaluru'), ('hydrabad', 'Hyderabad '), ('ahmadabad', 'Ahmadabad'), ('chennai', 'Chennai '), ('kolkata', 'Kolkata '), ('surat', 'Surat '), ('pune', 'Pune '), ('jaipur', 'Jaipur '), ('lucknow', 'Lucknow '), ('nashik', 'Nashik'), ('nagpur', 'Nagpur'), ('indore', 'Indore'), ('thane', 'Thane')], default='mumbai', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='seller_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_id_for_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.TextField(max_length=16, null=True, validators=[django.core.validators.MinLengthValidator(16, 'The Card number must have 16 digits')]),
        ),
        migrations.AlterField(
            model_name='sellingitem',
            name='item_category',
            field=models.CharField(blank=True, choices=[('art', 'Art'), ('antiques', 'Antiques'), ('books & magazines', 'Books & Magazines'), ('cameras & photo', 'Cameras & Photo'), ('cell phones & accessories', 'Cell Phones & Accessories'), ('clothing, shoes & accessories', 'Clothing, Shoes & Accessories'), ('coins & paper money', 'Coins & Paper Money'), ('collectibles', 'Collectibles'), ('computers/tablets & networking', 'Computers/Tablets & Networking'), ('consumer electronics', 'Consumer Electronics'), ('crafts', 'Crafts'), ('dolls & bears', 'Dolls & Bears'), ('everything else', 'Everything Else'), ('gift cards & coupons', 'Gift Cards & Coupons'), ('health & beauty', 'Health & Beauty'), ('jewelry & watches', 'Jewelry & Watches'), ('music', 'Music'), ('musical instruments & gear', 'Musical Instruments & Gear'), ('pet supplies', 'Pet Supplies'), ('pottery & glass', 'Pottery & Glass'), ('sporting goods', 'Sporting Goods'), ('stamps', 'Stamps'), ('tickets & experiences', 'Tickets & Experiences'), ('toys & hobbies', 'Toys & Hobbies'), ('video games & consoles', 'Video Games & Consoles')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sellingitem',
            name='item_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Auction',
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_id_for_transaction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.auctionitem'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_id_for_transaction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auctionwishlist',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auctionimage',
            name='auction_item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authenticate.auctionitem'),
        ),
        migrations.AddField(
            model_name='bid',
            name='auction_item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authenticate.auctionitem'),
        ),
    ]
