# Generated by Django 4.1.3 on 2023-06-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_auctionimage_auctionitem_auctionwishlist_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_mode',
            field=models.TextField(blank=True, null=True),
        ),
    ]
