# Generated by Django 4.1.3 on 2023-01-24 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_alter_images_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_status', models.BooleanField(blank=True, default=False, null=True)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellingItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=256)),
                ('item_description', models.TextField()),
                ('item_posted_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_sold', models.BooleanField(blank=True, default=False, null=True)),
                ('item_category', models.CharField(blank=True, max_length=256, null=True)),
                ('is_auction_item', models.BooleanField(blank=True, default=False, null=True)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='auction_item',
            name='seller_id',
        ),
        migrations.RemoveField(
            model_name='selling_item',
            name='seller_id',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='auction_expiry',
            new_name='Auction_expiry',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='auction_id',
            new_name='Auction_id',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='auction_id',
            new_name='Auction_id',
        ),
        migrations.RenameModel(
            old_name='images',
            new_name='Image',
        ),
        migrations.DeleteModel(
            name='orders',
        ),
        migrations.DeleteModel(
            name='selling_item',
        ),
        migrations.AddField(
            model_name='order',
            name='item_for_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authenticate.sellingitem'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.sellingitem'),
        ),
        migrations.AlterField(
            model_name='image',
            name='item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authenticate.sellingitem'),
        ),
        migrations.DeleteModel(
            name='auction_item',
        ),
    ]
