# Generated by Django 4.1.3 on 2023-01-31 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_order_sellingitem_remove_auction_item_seller_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellingitem',
            name='item_price',
            field=models.TextField(blank=True, null=True),
        ),
    ]
