# Generated by Django 4.1.3 on 2023-03-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_alter_customer_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_dispatched',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
