# Generated by Django 4.1.3 on 2023-01-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_sellingitem_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellingitem',
            name='item_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
