# Generated by Django 4.1.3 on 2023-03-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_auctionitem_transaction_remove_bid_auction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
