# Generated by Django 4.1.3 on 2023-02-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0006_wishlist_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='address2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='address3',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
