# Generated by Django 4.1.3 on 2023-03-22 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0008_auctionitem_posted_at_alter_auctionitem_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.auctionitem')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
