# Generated by Django 4.1.3 on 2023-03-22 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0009_auctionwishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
