# Generated by Django 4.1.3 on 2023-03-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0010_remove_customer_first_name_remove_customer_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='is_sold',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
