# Generated by Django 4.1.3 on 2023-03-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0011_auctionitem_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='item_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
